# Generated by Django 4.2.7 on 2023-11-21 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='numero_de_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='clientes.pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
