# Generated by Django 4.2.7 on 2023-11-26 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_producto_nombre_cliente_tipo_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='fecha_nacimiento',
            new_name='fecha_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_pedido',
        ),
    ]
